### ISSUE TITLE
Playlist playback from client ? (where do we stand?)

### ISSUE THREAD

**Issue by glucenag** [mopidy/mopidy-spotify#261]
Hey there,

after some research I am unclear as to where we stand regarding playlist playback ? From my Android client for mopidy (having installed mopidy-spotify and having a spotify premium account), I can't even see any spotify playlist (not those created by me nor those created by spotify). Searching for them does not result in any output. I can play normal albums just fine though. Note mopidy runs on a Raspberry Pi 3 (do not know whether that matters). The rest of mopidy features work perfectly. 

So anyway, after observing that I couldn't play any spotifiy playlists with mopidy-spotify (which I installed only recently, although I have been using mopidy for long now), I saw on the internet that somehow it was a known bug, but that there was some plan to fix it. I am not sure I understood everything, but then in the docs for the extension it still says that there should be support for playing playlists (read-only, it says), see https://github.com/mopidy/mopidy-spotify. 

So I'm sorry if this is a useless post but I felt like asking where we stand ? Is it supposed to work and this is a bug in my case only? Is it working in some versions and maybe I don't have the most recent version ? Should we be expecting a fix ?

Sorry if I'm out of place and thank you for all of this, anyway! 

Cheers!

**Comment by kingosticks** [comment]
It was fixed some time ago and works, as per the README. I would guess you don't have the most recent version. You should check that.

**Comment by glucenag** [comment]
That's what I figured but wanted to be sure. Will update and report back. Thanks!

**Comment by glucenag** [comment]
So I have run sudo apt update and sudo apt upgrade and I  believe I am now running the latest version of mopidy. `sudo mopidyctl deps` returns:

```
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf deps" as user mopidy
Executable: /usr/bin/mopidy
Platform: Linux-4.19.66-v7+-armv7l-with-debian-9.11
Python: CPython 2.7.13 from /usr/lib/python2.7
Mopidy: 2.2.3 from /usr/lib/python2.7/dist-packages
Mopidy-ALSAMixer: 1.0.3 from /usr/lib/python2.7/dist-packages
  Mopidy>=0.19: 2.2.3 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  pyalsaaudio: 0.7 from /usr/lib/python2.7/dist-packages
Mopidy-Local-SQLite: 1.0.0 from /usr/local/lib/python2.7/dist-packages
  Mopidy>=1.1: 2.2.3 from /usr/lib/python2.7/dist-packages
  setuptools: 33.1.1 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  uritools>=1.0: 2.2.0 from /usr/local/lib/python2.7/dist-packages
    ipaddress; python_version == "2.7": 1.0.17 from /usr/lib/python2.7/dist-packages
Mopidy-Spotify: 3.1.0 from /usr/lib/python2.7/dist-packages
  Mopidy>=2.0: 2.2.3 from /usr/lib/python2.7/dist-packages
  Pykka>=1.1: 1.2.1 from /usr/lib/python2.7/dist-packages
  pyspotify>=2.0.5: 2.0.5 from /usr/lib/python2.7/dist-packages
    cffi>=1.0.0: 1.9.1 from /usr/lib/python2.7/dist-packages
  requests>=2.0: 2.12.4 from /usr/lib/python2.7/dist-packages
GStreamer: 1.10.4.0 from /usr/lib/python2.7/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.22.0
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mad
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
```

Note I run mopidy as a service. 

I still can't see spotify playlists on mopidy. Is it that I need to also update the extension itself ?

Thanks !

**Comment by kingosticks** [comment]
Mopidy: v2.2.3 is *not* the latest version of Mopidy, if [you look](https://github.com/mopidy/mopidy/releases) you'll find it's v3.0.2. You need a 3.x version of Mopidy to install the version of Mopidy-Spotify with fixed playlist support. 

To install the latest version of Mopidy you need to install Mopidy in the way [documented](https://docs.mopidy.com/en/latest/installation/). You also need to be using a supported operating system. You have not mentioned what you are running but that version of GStreamer is very old so you must be running Raspbian Stretch? FYI we do not support Raspbian Stretch any more. 

I am going to close this issue as there is no bug in Mopidy-Spotify to track here. If, once you have read and carried out the documented install steps, you still need help installing Mopidy v3.x then please post in the [user support forum](https://discourse.mopidy.com/).
